//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Collections.ObjectModel;
using Kuka.FlexDrill.Process.CustomClasses;

namespace Kuka.FlexDrill.Process.OLPParser
{
// 
// Ce code source a été automatiquement généré par xsd, Version=4.6.1055.0.
// 


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class CellProgramXSD : object, System.ComponentModel.INotifyPropertyChanged {
    
      private Informations informationsField;
    
      private CustomerInfo customerInfoField;
    
      private CellConfiguration cellConfigurationField;
    
      private WorkSequence workSequenceField;
    
      private string schemaVersionField;
    
      /// <remarks/>
      public Informations Informations {
         get {
            return this.informationsField;
         }
         set {
            this.informationsField = value;
            this.RaisePropertyChanged("Informations");
         }
      }
    
      /// <remarks/>
      public CustomerInfo CustomerInfo {
         get {
            return this.customerInfoField;
         }
         set {
            this.customerInfoField = value;
            this.RaisePropertyChanged("CustomerInfo");
         }
      }
    
      /// <remarks/>
      public CellConfiguration CellConfiguration {
         get {
            return this.cellConfigurationField;
         }
         set {
            this.cellConfigurationField = value;
            this.RaisePropertyChanged("CellConfiguration");
         }
      }
    
      /// <remarks/>
      public WorkSequence WorkSequence {
         get {
            return this.workSequenceField;
         }
         set {
            this.workSequenceField = value;
            this.RaisePropertyChanged("WorkSequence");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string SchemaVersion {
         get {
            return this.schemaVersionField;
         }
         set {
            this.schemaVersionField = value;
            this.RaisePropertyChanged("SchemaVersion");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class Informations : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string programDateField;
    
      private string programmerNameField;
    
      private string oLPProgramNameField;
    
      private string oLPWorkCellField;
    
      private string oLPWorkCellPathField;
    
      private string oLPSoftwareVersionField;
    
      private string oLPDownloaderVersionField;
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string ProgramDate {
         get {
            return this.programDateField;
         }
         set {
            this.programDateField = value;
            this.RaisePropertyChanged("ProgramDate");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string ProgrammerName {
         get {
            return this.programmerNameField;
         }
         set {
            this.programmerNameField = value;
            this.RaisePropertyChanged("ProgrammerName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string OLPProgramName {
         get {
            return this.oLPProgramNameField;
         }
         set {
            this.oLPProgramNameField = value;
            this.RaisePropertyChanged("OLPProgramName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string OLPWorkCell {
         get {
            return this.oLPWorkCellField;
         }
         set {
            this.oLPWorkCellField = value;
            this.RaisePropertyChanged("OLPWorkCell");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string OLPWorkCellPath {
         get {
            return this.oLPWorkCellPathField;
         }
         set {
            this.oLPWorkCellPathField = value;
            this.RaisePropertyChanged("OLPWorkCellPath");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string OLPSoftwareVersion {
         get {
            return this.oLPSoftwareVersionField;
         }
         set {
            this.oLPSoftwareVersionField = value;
            this.RaisePropertyChanged("OLPSoftwareVersion");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string OLPDownloaderVersion {
         get {
            return this.oLPDownloaderVersionField;
         }
         set {
            this.oLPDownloaderVersionField = value;
            this.RaisePropertyChanged("OLPDownloaderVersion");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class CustomerInfo : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string commentField;
    
      private ObservableCollection<Info> infoField;
    
      /// <remarks/>
      public string Comment {
         get {
            return this.commentField;
         }
         set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Info")]
      public ObservableCollection<Info> LInfo {
         get {
            return this.infoField;
         }
         set {
            this.infoField = value;
            this.RaisePropertyChanged("LInfo");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class Info : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string nameField;
    
      private string valueField;
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Name {
         get {
            return this.nameField;
         }
         set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Value {
         get {
            return this.valueField;
         }
         set {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class CellConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
    
      private ConfigurationData configurationDataField;
    
      private string cellNameField;
    
      private string safetyNameField;
    
      private string partNameField;
    
      private string workZoneNameField;
    
      private string objectFrameNameField;
    
      private string operatingModeField;
    
      /// <remarks/>
      public ConfigurationData ConfigurationData {
         get {
            return this.configurationDataField;
         }
         set {
            this.configurationDataField = value;
            this.RaisePropertyChanged("ConfigurationData");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CellName {
         get {
            return this.cellNameField;
         }
         set {
            this.cellNameField = value;
            this.RaisePropertyChanged("CellName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string SafetyName {
         get {
            return this.safetyNameField;
         }
         set {
            this.safetyNameField = value;
            this.RaisePropertyChanged("SafetyName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string PartName {
         get {
            return this.partNameField;
         }
         set {
            this.partNameField = value;
            this.RaisePropertyChanged("PartName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string WorkZoneName {
         get {
            return this.workZoneNameField;
         }
         set {
            this.workZoneNameField = value;
            this.RaisePropertyChanged("WorkZoneName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string ObjectFrameName {
         get {
            return this.objectFrameNameField;
         }
         set {
            this.objectFrameNameField = value;
            this.RaisePropertyChanged("ObjectFrameName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string OperatingMode {
         get {
            return this.operatingModeField;
         }
         set {
            this.operatingModeField = value;
            this.RaisePropertyChanged("OperatingMode");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class ConfigurationData : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string objectFrameField;
    
      private string robotFrameField;
    
      private string robRootField;
    
      private string cADFrameField;
    
      private string externalAxisCountField;
    
      private string extAxisFrameField;
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string ObjectFrame {
         get {
            return this.objectFrameField;
         }
         set {
            this.objectFrameField = value;
            this.RaisePropertyChanged("ObjectFrame");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string RobotFrame {
         get {
            return this.robotFrameField;
         }
         set {
            this.robotFrameField = value;
            this.RaisePropertyChanged("RobotFrame");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string RobRoot {
         get {
            return this.robRootField;
         }
         set {
            this.robRootField = value;
            this.RaisePropertyChanged("RobRoot");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CADFrame {
         get {
            return this.cADFrameField;
         }
         set {
            this.cADFrameField = value;
            this.RaisePropertyChanged("CADFrame");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
      public string ExternalAxisCount {
         get {
            return this.externalAxisCountField;
         }
         set {
            this.externalAxisCountField = value;
            this.RaisePropertyChanged("ExternalAxisCount");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string ExtAxisFrame {
         get {
            return this.extAxisFrameField;
         }
         set {
            this.extAxisFrameField = value;
            this.RaisePropertyChanged("ExtAxisFrame");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class WorkSequence : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string commentField;
    
      private ObservableCollection<Operation> operationField;
    
      private string nameField;

      /// <remarks/>
      public string Comment {
         get {
            return this.commentField;
         }
         set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Operation")]
      public ObservableCollection<Operation> LOperation {
         get {
            return this.operationField;
         }
         set {
            this.operationField = value;
            this.RaisePropertyChanged("LOperation");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Name {
         get {
            return this.nameField;
         }
         set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
         }
      }

      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class OperationXSD : object, System.ComponentModel.INotifyPropertyChanged {
    
      private Correctors correctorsField;
    
      private RobotPoints robotPointsField;
    
      private string nameField;

      private string effectorField;

      /// <remarks/>
      public Correctors Correctors {
         get {
            return this.correctorsField;
         }
         set {
            this.correctorsField = value;
            this.RaisePropertyChanged("Correctors");
         }
      }
    
      /// <remarks/>
      public RobotPoints RobotPoints {
         get {
            return this.robotPointsField;
         }
         set {
            this.robotPointsField = value;
            this.RaisePropertyChanged("RobotPoints");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Name {
         get {
            return this.nameField;
         }
         set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Effector
      {
         get
         {
            return this.effectorField;
         }
         set
         {
            this.effectorField = value;
            this.RaisePropertyChanged("Effector");
         }
      }

      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class Correctors : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string commentField;
    
      private ObservableCollection<Corrector> correctorField;
    
      /// <remarks/>
      public string Comment {
         get {
            return this.commentField;
         }
         set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Corrector")]
      public ObservableCollection<Corrector> LCorrector {
         get {
            return this.correctorField;
         }
         set {
            this.correctorField = value;
            this.RaisePropertyChanged("LCorrector");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class Corrector : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string commentField;
    
      private ObservableCollection<Target> targetField;
    
      private string typeField;
    
      private string nameField;
    
      /// <remarks/>
      public string Comment {
         get {
            return this.commentField;
         }
         set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Target")]
      public ObservableCollection<Target> LTarget {
         get {
            return this.targetField;
         }
         set {
            this.targetField = value;
            this.RaisePropertyChanged("LTarget");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Type {
         get {
            return this.typeField;
         }
         set {
            this.typeField = value;
            this.RaisePropertyChanged("Type");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Name {
         get {
            return this.nameField;
         }
         set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class Target : object, System.ComponentModel.INotifyPropertyChanged {
        
      private string locationField;
        
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Location {
         get {
            return this.locationField;
         }
         set {
            this.locationField = value;
            this.RaisePropertyChanged("Location");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class RobotPoints : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string commentField;
    
      private ObservableCollection<RobotPoint> robotPointField;
    
      /// <remarks/>
      public string Comment {
         get {
            return this.commentField;
         }
         set {
            this.commentField = value;
            this.RaisePropertyChanged("Comment");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("RobotPoint")]
      public ObservableCollection<RobotPoint> LRobotPoint {
         get {
            return this.robotPointField;
         }
         set {
            this.robotPointField = value;
            this.RaisePropertyChanged("LRobotPoint");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class RobotPointXSD : object, System.ComponentModel.INotifyPropertyChanged {
    
      private ProcessData processDataField;
    
      private MotionData motionDataField;
    
      private string typeField;
    
      private string nameField;
           
      /// <remarks/>
      public ProcessData ProcessData {
         get {
            return this.processDataField;
         }
         set {
            this.processDataField = value;
            this.RaisePropertyChanged("ProcessData");
         }
      }
    
      /// <remarks/>
      public MotionData MotionData {
         get {
            return this.motionDataField;
         }
         set {
            this.motionDataField = value;
            this.RaisePropertyChanged("MotionData");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Type {
         get {
            return this.typeField;
         }
         set {
            this.typeField = value;
            this.RaisePropertyChanged("Type");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Name {
         get {
            return this.nameField;
         }
         set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
         }
      }
        
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class ProcessData : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string processField;
    
      private string messageField;
    
      private string fastenerField;
    
      private string patternNameField;
    
      private string clampingForceField;
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Process {
         get {
            return this.processField;
         }
         set {
            this.processField = value;
            this.RaisePropertyChanged("Process");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Message {
         get {
            return this.messageField;
         }
         set {
            this.messageField = value;
            this.RaisePropertyChanged("Message");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Fastener {
         get {
            return this.fastenerField;
         }
         set {
            this.fastenerField = value;
            this.RaisePropertyChanged("Fastener");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string PatternName {
         get {
            return this.patternNameField;
         }
         set {
            this.patternNameField = value;
            this.RaisePropertyChanged("PatternName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string ClampingForce {
         get {
            return this.clampingForceField;
         }
         set {
            this.clampingForceField = value;
            this.RaisePropertyChanged("ClampingForce");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
   public partial class MotionData : object, System.ComponentModel.INotifyPropertyChanged {
    
      private string locationField;
    
      private string correctorNameField;
    
      private string motionTypeField;
    
      private string motionSpeedField;
    
      private string escapeFrameField;
    
      private string offsetFrameField;
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string Location {
         get {
            return this.locationField;
         }
         set {
            this.locationField = value;
            this.RaisePropertyChanged("Location");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CorrectorName {
         get {
            return this.correctorNameField;
         }
         set {
            this.correctorNameField = value;
            this.RaisePropertyChanged("CorrectorName");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string MotionType {
         get {
            return this.motionTypeField;
         }
         set {
            this.motionTypeField = value;
            this.RaisePropertyChanged("MotionType");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string MotionSpeed {
         get {
            return this.motionSpeedField;
         }
         set {
            this.motionSpeedField = value;
            this.RaisePropertyChanged("MotionSpeed");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string EscapeFrame {
         get {
            return this.escapeFrameField;
         }
         set {
            this.escapeFrameField = value;
            this.RaisePropertyChanged("EscapeFrame");
         }
      }
    
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string OffsetFrame {
         get {
            return this.offsetFrameField;
         }
         set {
            this.offsetFrameField = value;
            this.RaisePropertyChanged("OffsetFrame");
         }
      }
    
      public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
      protected void RaisePropertyChanged(string propertyName) {
         System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
         if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
         }
      }
   }
}